export const site = {
  name: "Keanu Agustin",
  firstName: "Keanu",
  role: "Software Developer",
  tagline: "Programmer who Builds",
  location: "Valenzuela, Philippines",
  locationShort: "VALENZUELA, PHILIPPINES",
  email: "keanuagustin.tech@gmail.com",
  available: true,
  availableLabel: "Available for work",
  heroEyebrow: "HELLO, I'M KEANU AGUSTIN. A -",
  heroVertical: "DESIGN / CODE / DETAILS",
  heroLine: "PROGRAMMER WHO",
  heroRoll: ["design", "build", "ship", "solve"],
  intro: {
    lead: "I study software development and deep learning. Now I engineer intelligent systems and interfaces people actually want to use.",
    body: "From audio processing research to blockchain marketplaces, I help teams ship software that works, scales, and solves real problems.",
  },
  about: {
    heading: "I build the systems people rely on — and the tools that let teams move fast.",
    paragraphs: [
      "I started in low-level programming, where every function has to be carefully planned and every step needs an understanding of program flow. That discipline stuck with me, because in the age of agentic development, I still want to know how everything works and why it works.",
      "I work across mobile, web, blockchain, and applied AI — enough range to prototype the thing instead of just describing it. But building rarely happens alone. I work well in teams, communicate clearly across research, design, and engineering, and I'm comfortable picking up whatever the team needs, from debugging someone else's code to documenting a system for the next person.",
      "The goal is always the same: software people can trust, built by people who trust each other.",
    ],
  },
  footer: {
    sub: "Systems, interfaces, and the unglamorous parts in between. Open to teams that care about the last 5%.",
    headline: "Press play on the next idea",
    subtitle: "Contact me",
    credit: "Created by Keanu Agustin",
  },
  contact: {
    eyebrow: "AVAILABLE FOR NEW PROJECTS",
    title: "Cue the next track?",
    intro: "Send a brief. I’ll reply within a couple of days.",
    successTitle: "Tape loaded.",
    successBody: "Thanks — I’ll be in touch soon.",
  },
  socials: [
    { label: "LinkedIn", href: "https://www.linkedin.com/in/keanuagustin31/" },
    { label: "GitHub", href: "https://github.com/geadlydrim" },
  ],
  featuredOn: [
    "TensorFlow",
    "JS/TS",
    "Web3.js/Solidity",
    "AutoHotkey",
    "Python",
    "Selenium",
    "Playwright",
    "React",
    "Kotlin",
    "VirtualBox",
    "Bash/Shell",
    "C++",
    "LangChain",
    "Node.js",
    "React Native",
    "Rust",
    "Java",
    "Git/GitHub",
    "PyTorch",
    "SQL/NoSQL",
    "OpenCV",
  ],
  audioSrc: "/audio/mineral-serenading.mp3?v=2",
  audioDuration: 324.62,
  audioTitle: "Side A · Mineral — &Serenading",
  audioArt: "/audio/endserenading.jpg",
  avatar: "/avatar.jpg?v=2",
} as const;

export type Site = typeof site;
